import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
LC_ALL = "en_US.UTF-8"

[window]
decorations = "Full"
opacity = 0.95

[font]
normal.family = "CaskaydiaCove Nerd Font"
normal.style = "Regular"
size = 11

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true
