import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
position.x = 1301
position.y = 168
dimensions.columns = 148
dimensions.lines = 41
decorations = "None"
opacity = 0.985
blur = true

[font]
normal.family = "CaskaydiaCove Nerd Font"
normal.style = "Regular"
size = 11

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true
