add_newline = true

[c]
symbol = " "

[cmake]
symbol = "󰔷 "

[haskell]
symbol = " "

[lua]
symbol = " "

[package]
symbol = "󰏓 "

[python]
symbol = " "

[rust]
symbol = " "

[battery]
disabled = true
