#! /bin/bash
rofi_command="rofi -theme config/networkmanager.rasi"
rofi_scripts_path="$HOME/.config/rofi/bin"

wifi_points=$(nmcli -f SSID,SIGNAL dev wifi | awk -F'  +' 'NR>1 && $1 != "--" {print $1}' | sort -u)

echo -e "$wifi_points"

selected_wifi=$(echo -e "$wifi_points" | $rofi_command -dmenu)

if [[ -z "$selected_wifi" ]]; then
    exit
fi

nmcli connection show "$selected_wifi" | grep 802-11-wireless-security.psk
if [[ $? -eq 1 ]]; then
    echo $?
    password="password $("$rofi_scripts_path"/password "Password for \"$selected_wifi\":")"
fi


echo "Connecting to $selected_wifi with $password"
nmcli device wifi connect "$selected_wifi" $password
if [[ $? -ne 0 ]]; then
    echo "Cannot connect to $selected_wifi"
fi
