# import = [
#   "~/.config/alacritty/gruvbox-material.yml"
# ]

[env]
# TERM = "tmux-256color"
LC_ALL = "en_US.UTF-8"

[window]
decorations = "Full"
opacity = 0.95

[font]
normal.family = "CaskaydiaCove Nerd Font"
normal.style = "Regular"
size = 10

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true
